<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ArticuloTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('articulo')->delete();
        
        \DB::table('articulo')->insert(array (
            0 => 
            array (
                'id' => 5,
                'id_prestashop' => 31,
            'nombre' => 'Pizza Ultra Grande (45cm)',
                'ref' => 'PG45',
            'descripcion' => 'Pizza Ultra Grande (45cm) 10ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 10,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '4.60',
                'cantidad' => 100,
                'id_tipo_etiqueta' => 1,
                'precio' => '24.09',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 27,
                'sorting_index' => 18,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-23',
            ),
            1 => 
            array (
                'id' => 6,
                'id_prestashop' => 52,
            'nombre' => 'Pizza Allargata Grande (40 x 35cm)',
                'ref' => 'PAG4025',
            'descripcion' => 'Pizza Allargata Grande (40 x 35cm) 10ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 10,
                'id_familia' => NULL,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '4.70',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '19.00',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => 25,
                'sorting_index' => 23,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-05',
            ),
            2 => 
            array (
                'id' => 7,
                'id_prestashop' => 53,
            'nombre' => 'Pizza Grande Reffinata (40cm)',
                'ref' => 'PGR40',
            'descripcion' => 'Pizza Grande Reffinata (40cm) 12ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 12,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '4.80',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '17.33',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 24,
                'sorting_index' => 16,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-04',
            ),
            3 => 
            array (
                'id' => 8,
                'id_prestashop' => 54,
            'nombre' => 'Pizza Single (20cm)',
                'ref' => 'PS20',
            'descripcion' => 'Pizza Single (20cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '2.50',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '13.91',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 22,
                'sorting_index' => 0,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-24',
            ),
            4 => 
            array (
                'id' => 9,
                'id_prestashop' => 55,
            'nombre' => 'Pizza Mediana Americana (32cm)',
                'ref' => 'PMA32',
            'descripcion' => 'Pizza Mediana Americana (32cm) 10ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 10,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '4.60',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '18.19',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 25,
                'sorting_index' => 13,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-04',
            ),
            5 => 
            array (
                'id' => 10,
                'id_prestashop' => 57,
            'nombre' => 'Pizza Grande (40cm)',
                'ref' => 'PG40',
            'descripcion' => 'Pizza Grande (40cm) 10ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 10,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '4.60',
                'cantidad' => 960,
                'id_tipo_etiqueta' => 1,
                'precio' => '19.26',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 25,
                'sorting_index' => 6,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-13',
            ),
            6 => 
            array (
                'id' => 11,
                'id_prestashop' => 58,
            'nombre' => 'Pizza Allargata Mediana (30x18cm)',
                'ref' => 'PAM3018',
            'descripcion' => 'Pizza Allargata Mediana (30x18cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '4.95',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '25.25',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 24,
                'sorting_index' => 14,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-08-26',
            ),
            7 => 
            array (
                'id' => 12,
                'id_prestashop' => 59,
            'nombre' => 'Pizza Pequeña de 100% Espelta Integral (24cm)',
                'ref' => 'PP100EI24',
            'descripcion' => 'Pizza Pequeña de 100% Espelta Integral (24cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '2.95',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '31.02',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => 30,
                'sorting_index' => 11,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-04-01',
            ),
            8 => 
            array (
                'id' => 13,
                'id_prestashop' => 60,
            'nombre' => 'Pizza Mediana (32cm)',
                'ref' => 'PM32',
            'descripcion' => 'Pizza Mediana (32cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '5.01',
                'cantidad' => 1100,
                'id_tipo_etiqueta' => 1,
                'precio' => '25.68',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 24,
                'sorting_index' => 4,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-24',
            ),
            9 => 
            array (
                'id' => 14,
                'id_prestashop' => 62,
            'nombre' => 'Pizza Pequeña (24cm)',
                'ref' => 'PP24',
            'descripcion' => 'Pizza Pequeña (24cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '2.95',
                'cantidad' => 38,
                'id_tipo_etiqueta' => 1,
                'precio' => '16.05',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 23,
                'sorting_index' => 3,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-24',
            ),
            10 => 
            array (
                'id' => 15,
                'id_prestashop' => 63,
            'nombre' => 'Pizza Pequeña Americana (25cm)',
                'ref' => 'PPA25',
            'descripcion' => 'Pizza Pequeña Americana (25cm) 10ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 10,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '2.48',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '10.16',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 24,
                'sorting_index' => 9,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-03',
            ),
            11 => 
            array (
                'id' => 16,
                'id_prestashop' => 64,
            'nombre' => 'Pizza Grande Americana (40cm)',
                'ref' => 'PGA40',
            'descripcion' => 'Pizza Grande Americana (40cm) 10ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 10,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '6.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '23.55',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 27,
                'sorting_index' => 17,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-03',
            ),
            12 => 
            array (
                'id' => 17,
                'id_prestashop' => 65,
            'nombre' => 'Pizza Mediana Reffinata (30cm)',
                'ref' => 'PMR30',
            'descripcion' => 'Pizza Mediana Reffinata (30cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '2.95',
                'cantidad' => 280,
                'id_tipo_etiqueta' => 1,
                'precio' => '21.40',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 23,
                'sorting_index' => 13,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-06',
            ),
            13 => 
            array (
                'id' => 18,
                'id_prestashop' => 66,
            'nombre' => 'Pizza Mediana (30cm)',
                'ref' => 'PM30',
            'descripcion' => 'Pizza Mediana (30cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '5.01',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '23.55',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 24,
                'sorting_index' => 3,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-24',
            ),
            14 => 
            array (
                'id' => 19,
                'id_prestashop' => 67,
            'nombre' => 'Pizza Allargata Pequeña (24x15cm)',
                'ref' => 'PAP2415',
            'descripcion' => 'Pizza Allargata Pequeña (24x15cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '2.95',
                'cantidad' => 140,
                'id_tipo_etiqueta' => 1,
                'precio' => '17.34',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 23,
                'sorting_index' => 10,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-24',
            ),
            15 => 
            array (
                'id' => 20,
                'id_prestashop' => 68,
            'nombre' => 'Pizza Mediana (35cm)',
                'ref' => 'PM35',
            'descripcion' => 'Pizza Mediana (35cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '7.10',
                'cantidad' => 100,
                'id_tipo_etiqueta' => 1,
                'precio' => '30.39',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 26,
                'sorting_index' => 5,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-05',
            ),
            16 => 
            array (
                'id' => 21,
                'id_prestashop' => 69,
            'nombre' => 'Pizza Cuadrada (30x40cm)',
                'ref' => 'PC3040',
            'descripcion' => 'Pizza Cuadrada (30x40cm) 8ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 8,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '5.15',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '19.69',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 27,
                'sorting_index' => 7,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-04',
            ),
            17 => 
            array (
                'id' => 22,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Single',
                'ref' => 'AMABOLAPS20',
                'descripcion' => 'Bola Single 90gr.',
                'unidades_torre' => 25,
                'unidades_caja' => 15,
                'id_familia' => 1,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '0.16',
                'cantidad' => 6501,
                'id_tipo_etiqueta' => 1,
                'precio' => '0.00',
                'principal' => 1,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 1,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-06',
            ),
            18 => 
            array (
                'id' => 23,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Pequeña',
                'ref' => 'AMABOLAPP24',
                'descripcion' => 'Bola Pequeña 160gr.',
                'unidades_torre' => 25,
                'unidades_caja' => 8,
                'id_familia' => 1,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '0.16',
                'cantidad' => 58552,
                'id_tipo_etiqueta' => 1,
                'precio' => '0.00',
                'principal' => 1,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 2,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-06',
            ),
            19 => 
            array (
                'id' => 24,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Mediana',
                'ref' => 'AMABOLAMED30',
                'descripcion' => 'Bola Mediana 250gr.',
                'unidades_torre' => 15,
                'unidades_caja' => 8,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.25',
                'cantidad' => 33280,
                'id_tipo_etiqueta' => 1,
                'precio' => '0.00',
                'principal' => 1,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 3,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-04',
            ),
            20 => 
            array (
                'id' => 25,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Grande',
                'ref' => 'AMABOLAGR40',
                'descripcion' => 'Bola Grande 450gr.',
                'unidades_torre' => 15,
                'unidades_caja' => 6,
                'id_familia' => 1,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '0.45',
                'cantidad' => 5040,
                'id_tipo_etiqueta' => 1,
                'precio' => '0.00',
                'principal' => 1,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 4,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-11',
            ),
            21 => 
            array (
                'id' => 26,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Mediana 35',
                'ref' => 'AMABOLAMED35',
                'descripcion' => 'Bola Mediana 35 350gr.',
                'unidades_torre' => 15,
                'unidades_caja' => 6,
                'id_familia' => 1,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '0.35',
                'cantidad' => 822,
                'id_tipo_etiqueta' => 1,
                'precio' => '0.00',
                'principal' => 1,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 5,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-08-27',
            ),
            22 => 
            array (
                'id' => 27,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Plancha 30x40',
                'ref' => 'AMABOLACU4030',
                'descripcion' => 'Bola Plancha 30x40 600gr.',
                'unidades_torre' => 15,
                'unidades_caja' => 3,
                'id_familia' => 1,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '0.60',
                'cantidad' => 876,
                'id_tipo_etiqueta' => 1,
                'precio' => '0.00',
                'principal' => 1,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 6,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-09-04',
            ),
            23 => 
            array (
                'id' => 28,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Midis',
                'ref' => 'AMABOLAMIDI',
                'descripcion' => 'Bola Midi 100gr.',
                'unidades_torre' => 25,
                'unidades_caja' => 12,
                'id_familia' => 1,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 804,
                'id_tipo_etiqueta' => 1,
                'precio' => '0.00',
                'principal' => 1,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 7,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-06-18',
            ),
            24 => 
            array (
                'id' => 29,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Panecillos',
                'ref' => 'AMABOLAPAN',
                'descripcion' => 'Bola Panecillo 80gr.',
                'unidades_torre' => 25,
                'unidades_caja' => 15,
                'id_familia' => 1,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 375,
                'id_tipo_etiqueta' => 1,
                'precio' => '0.00',
                'principal' => 1,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 8,
                'created_at' => '2023-03-31',
                'updated_at' => '2024-05-29',
            ),
            25 => 
            array (
                'id' => 30,
                'id_prestashop' => NULL,
                'nombre' => 'Bola 100% Espelta Pequeña',
                'ref' => 'AMABOLA100ESPELPE24',
                'descripcion' => 'Bola 100% Espelta Pequeña 160gr.',
                'unidades_torre' => 25,
                'unidades_caja' => 8,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.16',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 15,
                'created_at' => '2023-07-19',
                'updated_at' => '2024-06-20',
            ),
            26 => 
            array (
                'id' => 34,
                'id_prestashop' => NULL,
                'nombre' => 'Bola 50% Espelta Mediana',
                'ref' => 'AMOBOLA50ESPELME30',
                'descripcion' => 'Bola 50% Espelta Mediana 250gr.',
                'unidades_torre' => 15,
                'unidades_caja' => 8,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.25',
                'cantidad' => 0,
                'id_tipo_etiqueta' => 1,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 55,
                'created_at' => '2023-07-20',
                'updated_at' => '2024-06-20',
            ),
            27 => 
            array (
                'id' => 35,
                'id_prestashop' => NULL,
            'nombre' => 'Pizza Pequeña (27cm)',
                'ref' => 'PP27',
            'descripcion' => 'Pizza Pequeña (27cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.16',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 48,
                'sorting_index' => 8,
                'created_at' => '2023-07-21',
                'updated_at' => '2024-04-08',
            ),
            28 => 
            array (
                'id' => 36,
                'id_prestashop' => NULL,
            'nombre' => 'Pizza Mediana (28cm)',
                'ref' => 'PM28',
            'descripcion' => 'Pizza Mediana (28cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '5.01',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 24,
                'sorting_index' => 15,
                'created_at' => '2023-07-21',
                'updated_at' => '2024-08-29',
            ),
            29 => 
            array (
                'id' => 37,
                'id_prestashop' => NULL,
            'nombre' => 'Pizza Mediana Grossa (35cm)',
                'ref' => 'PMG35',
            'descripcion' => 'Pizza Mediana Grossa (35cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => 25,
                'sorting_index' => 15,
                'created_at' => '2023-07-21',
                'updated_at' => '2024-03-19',
            ),
            30 => 
            array (
                'id' => 38,
                'id_prestashop' => NULL,
                'nombre' => 'Bola 50% Espelta Pequeña',
                'ref' => 'AMABOLA50ESPELPE24',
                'descripcion' => 'Bola 50% Espelta Pequeña 160gr.',
                'unidades_torre' => 25,
                'unidades_caja' => 8,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.16',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 60,
                'created_at' => '2023-07-21',
                'updated_at' => '2024-06-20',
            ),
            31 => 
            array (
                'id' => 39,
                'id_prestashop' => NULL,
            'nombre' => 'Pizza Pequeña de 50% Espelta Integral (24cm)',
                'ref' => 'PP50EI24',
            'descripcion' => 'Pizza Pequeña de 50% Espelta Integral (24cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '2.95',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '31.02',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 38,
                'sorting_index' => 12,
                'created_at' => '2023-07-21',
                'updated_at' => '2024-04-01',
            ),
            32 => 
            array (
                'id' => 40,
                'id_prestashop' => NULL,
            'nombre' => 'Pizza Mediana de 50% Espelta (30cm)',
                'ref' => 'PM50E30',
            'descripcion' => 'Pizza Mediana de 50% Espelta (30cm) 20ud.',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => NULL,
                'id_fabricante' => NULL,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => 34,
                'sorting_index' => 21,
                'created_at' => '2023-07-21',
                'updated_at' => '2024-03-19',
            ),
            33 => 
            array (
                'id' => 42,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Mediana en caja Peq. 8 uds.',
                'ref' => 'AMABOLAMED30PEQ',
                'descripcion' => 'Bola Mediana 250gr. en caja Peq. 8 uds.',
                'unidades_torre' => 25,
                'unidades_caja' => 8,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.25',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 75,
                'created_at' => '2024-01-15',
                'updated_at' => '2024-06-20',
            ),
            34 => 
            array (
                'id' => 43,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Mediana 10 Unidades',
                'ref' => 'AMABOLAMED3010',
                'descripcion' => 'Bola Mediana 250gr. 10 ud/caja',
                'unidades_torre' => 15,
                'unidades_caja' => 10,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.25',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 1,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 0,
                'created_at' => '2024-01-15',
                'updated_at' => '2024-02-22',
            ),
            35 => 
            array (
                'id' => 44,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Mediana en caja Peq. 10 uds.',
                'ref' => 'AMABOLAMED30PEQ10',
                'descripcion' => 'Bola Mediana 250gr. en caja Peq. 10 uds.',
                'unidades_torre' => 25,
                'unidades_caja' => 10,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.25',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 70,
                'created_at' => '2024-01-15',
                'updated_at' => '2024-06-20',
            ),
            36 => 
            array (
                'id' => 45,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Pequeña en caja Med. 8 uds.',
                'ref' => 'AMABOLAPP24MED',
                'descripcion' => 'Bola Pequeña 160gr. en caja Med. 8 uds.',
                'unidades_torre' => 15,
                'unidades_caja' => 8,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.16',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 90,
                'created_at' => '2024-01-15',
                'updated_at' => '2024-06-20',
            ),
            37 => 
            array (
                'id' => 46,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Pequeña 11 Unidades',
                'ref' => 'AMABOLAPP2411',
                'descripcion' => 'Bola Pequeña 160 gr. 11 unidades',
                'unidades_torre' => 25,
                'unidades_caja' => 11,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.16',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 80,
                'created_at' => '2024-01-15',
                'updated_at' => '2024-06-20',
            ),
            38 => 
            array (
                'id' => 47,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Pequeña en caja Peq. 11 uds.',
                'ref' => 'AMABOLAPP24MED11',
                'descripcion' => 'Bola Pequeña 160gr. en caja Med. 11 uds.',
                'unidades_torre' => 15,
                'unidades_caja' => 11,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.16',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 120,
                'created_at' => '2024-01-15',
                'updated_at' => '2024-06-20',
            ),
            39 => 
            array (
                'id' => 48,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Verona 190gr.',
                'ref' => 'AMABOLAVERONA',
                'descripcion' => 'Bola Verona 190gr. en caja Med. 8 uds',
                'unidades_torre' => 15,
                'unidades_caja' => 8,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.19',
                'cantidad' => 2160,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 1,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 16,
                'created_at' => '2024-01-15',
                'updated_at' => '2024-09-02',
            ),
            40 => 
            array (
                'id' => 49,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Verona 190gr. en caja Med. 10 uds.',
                'ref' => 'AMABOLAVERONA10',
                'descripcion' => 'Bola Verona 190gr. en caja Med. 10 uds.',
                'unidades_torre' => 15,
                'unidades_caja' => 10,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.19',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 150,
                'created_at' => '2024-01-15',
                'updated_at' => '2024-06-20',
            ),
            41 => 
            array (
                'id' => 50,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Verona 190gr. en caja Peq. 8 uds.',
                'ref' => 'AMABOLAVERONAPEQ8',
                'descripcion' => 'Bola Verona 190gr. en caja Peq. 8 uds.',
                'unidades_torre' => 25,
                'unidades_caja' => 8,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.19',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 200,
                'created_at' => '2024-01-15',
                'updated_at' => '2024-06-20',
            ),
            42 => 
            array (
                'id' => 51,
                'id_prestashop' => NULL,
                'nombre' => 'Bola Verona 190gr. caja Peq. 10 uds.',
                'ref' => 'AMABOLAVERONAPEQ10',
                'descripcion' => 'Bola Verona 190gr. caja Peq. 10 uds.',
                'unidades_torre' => 25,
                'unidades_caja' => 10,
                'id_familia' => 1,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.19',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 130,
                'created_at' => '2024-01-15',
                'updated_at' => '2024-06-20',
            ),
            43 => 
            array (
                'id' => 53,
                'id_prestashop' => NULL,
            'nombre' => 'Pizza Pequeña Ametller (24cm)',
                'ref' => 'PAP24AMETLL',
            'descripcion' => 'Pizza Pequeña Ametller (24cm) 40 uds.',
                'unidades_torre' => 0,
                'unidades_caja' => 40,
                'id_familia' => NULL,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.16',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 23,
                'sorting_index' => 2,
                'created_at' => '2024-02-02',
                'updated_at' => '2024-09-06',
            ),
            44 => 
            array (
                'id' => 54,
                'id_prestashop' => NULL,
                'nombre' => 'SP Single',
                'ref' => 'SPPS20',
            'descripcion' => 'Pizza Single Servipizza (20 ud. por paquete)',
                'unidades_torre' => 0,
                'unidades_caja' => 20,
                'id_familia' => 2,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '160.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '13.91',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 22,
                'sorting_index' => 19,
                'created_at' => '2024-03-15',
                'updated_at' => '2024-04-01',
            ),
            45 => 
            array (
                'id' => 55,
                'id_prestashop' => NULL,
                'nombre' => 'SP Pequeña',
                'ref' => 'SPPP24',
            'descripcion' => 'Pizza Pequeña Servipizza (15 ud. por paquete)',
                'unidades_torre' => 0,
                'unidades_caja' => 15,
                'id_familia' => 2,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '160.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '6.02',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 23,
                'sorting_index' => 20,
                'created_at' => '2024-03-18',
                'updated_at' => '2024-04-01',
            ),
            46 => 
            array (
                'id' => 56,
                'id_prestashop' => NULL,
                'nombre' => 'SP Mediana',
                'ref' => 'SPPM30',
            'descripcion' => 'Pizza Mediana Servipizza (10 ud. por paquete)',
                'unidades_torre' => 0,
                'unidades_caja' => 10,
                'id_familia' => 2,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '240.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '5.88',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 24,
                'sorting_index' => 21,
                'created_at' => '2024-03-18',
                'updated_at' => '2024-04-01',
            ),
            47 => 
            array (
                'id' => 57,
                'id_prestashop' => NULL,
                'nombre' => 'SP Grandes',
                'ref' => 'SPPG40',
            'descripcion' => 'Pizza Grande Servipizza (5 ud. por paquete)',
                'unidades_torre' => 0,
                'unidades_caja' => 5,
                'id_familia' => 2,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '450.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '4.82',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 25,
                'sorting_index' => 22,
                'created_at' => '2024-03-18',
                'updated_at' => '2024-04-01',
            ),
            48 => 
            array (
                'id' => 58,
                'id_prestashop' => NULL,
                'nombre' => 'SP Cuadrada',
                'ref' => 'SPPC3040',
            'descripcion' => 'Pizza Plancha Servipizza (5 ud. por paquete)',
                'unidades_torre' => 0,
                'unidades_caja' => 5,
                'id_familia' => 2,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '6.10',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 27,
                'sorting_index' => 23,
                'created_at' => '2024-03-18',
                'updated_at' => '2024-04-01',
            ),
            49 => 
            array (
                'id' => 59,
                'id_prestashop' => NULL,
                'nombre' => 'SP Midi',
                'ref' => 'SPMIDI',
            'descripcion' => 'Midis Servipizza (4 ud. por paquete)',
                'unidades_torre' => 0,
                'unidades_caja' => 4,
                'id_familia' => 2,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '1.92',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 28,
                'sorting_index' => 24,
                'created_at' => '2024-03-18',
                'updated_at' => '2024-04-01',
            ),
            50 => 
            array (
                'id' => 60,
                'id_prestashop' => NULL,
                'nombre' => 'Panecillos',
                'ref' => 'PAN',
            'descripcion' => 'Panecillos Verona (10 ud. por paquete)',
                'unidades_torre' => 0,
                'unidades_caja' => 10,
                'id_familia' => 2,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.35',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 29,
                'sorting_index' => 25,
                'created_at' => '2024-03-18',
                'updated_at' => '2024-04-01',
            ),
            51 => 
            array (
                'id' => 61,
                'id_prestashop' => NULL,
                'nombre' => 'Focaccia Verona',
                'ref' => 'SPFOC',
            'descripcion' => 'Focaccia Verona (4 ud. por paquete)',
                'unidades_torre' => 0,
                'unidades_caja' => 4,
                'id_familia' => 2,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '6.10',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => 23,
                'sorting_index' => 26,
                'created_at' => '2024-03-18',
                'updated_at' => '2024-04-01',
            ),
            52 => 
            array (
                'id' => 62,
                'id_prestashop' => NULL,
                'nombre' => 'Bolsa Palet Amet Single 300x350',
                'ref' => 'BPAMET',
                'descripcion' => 'Bolsa Palet pequeñas de 2 en 2 y single',
                'unidades_torre' => 0,
                'unidades_caja' => 0,
                'id_familia' => 3,
                'id_fabricante' => 3,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.06',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => NULL,
                'sorting_index' => 15,
                'created_at' => '2024-05-16',
                'updated_at' => '2024-09-04',
            ),
            53 => 
            array (
                'id' => 63,
                'id_prestashop' => NULL,
                'nombre' => 'Bolsa Pequeña 360x400',
                'ref' => 'BPEQ',
                'descripcion' => 'Bolsas para pequeñas de 5 en 5',
                'unidades_torre' => 0,
                'unidades_caja' => 0,
                'id_familia' => 3,
                'id_fabricante' => 5,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.07',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => NULL,
                'sorting_index' => 16,
                'created_at' => '2024-05-16',
                'updated_at' => '2024-09-04',
            ),
            54 => 
            array (
                'id' => 64,
                'id_prestashop' => NULL,
                'nombre' => 'Bolsa Mediana 420x450',
                'ref' => 'BMED',
                'descripcion' => 'Bolsa Mediana 5 en 5',
                'unidades_torre' => 0,
                'unidades_caja' => 0,
                'id_familia' => 3,
                'id_fabricante' => 5,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.10',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => NULL,
                'sorting_index' => 17,
                'created_at' => '2024-05-16',
                'updated_at' => '2024-09-04',
            ),
            55 => 
            array (
                'id' => 65,
                'id_prestashop' => NULL,
                'nombre' => 'Bolsa Grande 50x55',
                'ref' => 'BGRAN',
                'descripcion' => 'Bolsa para envasar 5 grandes o 4 cuadradas 30x40 o Granel SP',
                'unidades_torre' => 0,
                'unidades_caja' => 0,
                'id_familia' => 3,
                'id_fabricante' => 2,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.13',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => NULL,
                'sorting_index' => 16,
                'created_at' => '2024-05-16',
                'updated_at' => '2024-05-17',
            ),
            56 => 
            array (
                'id' => 67,
                'id_prestashop' => NULL,
                'nombre' => 'Caja Cartón Montada',
                'ref' => 'CCAMET',
                'descripcion' => 'Caja Montada Cartón Palet Ametller',
                'unidades_torre' => 0,
                'unidades_caja' => 0,
                'id_familia' => 4,
                'id_fabricante' => 6,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => NULL,
                'sorting_index' => 1,
                'created_at' => '2024-09-04',
                'updated_at' => '2024-09-04',
            ),
            57 => 
            array (
                'id' => 68,
                'id_prestashop' => NULL,
                'nombre' => 'Caja Cartón Pequeña',
                'ref' => 'CPEQ',
                'descripcion' => 'Caja Cartón Pequeña 270x270x185',
                'unidades_torre' => 0,
                'unidades_caja' => 0,
                'id_familia' => NULL,
                'id_fabricante' => 7,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => NULL,
                'sorting_index' => 1,
                'created_at' => '2024-09-04',
                'updated_at' => '2024-09-04',
            ),
            58 => 
            array (
                'id' => 69,
                'id_prestashop' => NULL,
                'nombre' => 'Caja Cartón Mediana',
                'ref' => 'CCMED',
                'descripcion' => 'Caja Cartón Mediana 350x350x187',
                'unidades_torre' => 0,
                'unidades_caja' => 0,
                'id_familia' => 4,
                'id_fabricante' => 7,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => NULL,
                'sorting_index' => 1,
                'created_at' => '2024-09-04',
                'updated_at' => '2024-09-04',
            ),
            59 => 
            array (
                'id' => 70,
                'id_prestashop' => NULL,
                'nombre' => 'Caja Cartón Grande',
                'ref' => 'CCGRAND',
                'descripcion' => 'Caja Cartón Grande 435x435x128',
                'unidades_torre' => 0,
                'unidades_caja' => 0,
                'id_familia' => 4,
                'id_fabricante' => 7,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => NULL,
                'sorting_index' => 3,
                'created_at' => '2024-09-04',
                'updated_at' => '2024-09-04',
            ),
            60 => 
            array (
                'id' => 71,
                'id_prestashop' => NULL,
                'nombre' => 'Bolsa Grande Internet 40x50',
                'ref' => 'BGRAINT',
                'descripcion' => 'Bolsa para envasar Grande Internet',
                'unidades_torre' => 0,
                'unidades_caja' => 0,
                'id_familia' => 3,
                'id_fabricante' => 2,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 0,
                'id_produccion' => NULL,
                'sorting_index' => 5,
                'created_at' => '2024-09-04',
                'updated_at' => '2024-09-04',
            ),
            61 => 
            array (
                'id' => 72,
                'id_prestashop' => NULL,
                'nombre' => 'Etiqueta Lote RGSEAA',
                'ref' => 'ETIQ',
                'descripcion' => 'Etiqueta lote RGSEAA e ingredientes',
                'unidades_torre' => 0,
                'unidades_caja' => 0,
                'id_familia' => 7,
                'id_fabricante' => 8,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 0,
                'id_tipo_etiqueta' => NULL,
                'precio' => '0.00',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => NULL,
                'sorting_index' => 1,
                'created_at' => '2024-09-04',
                'updated_at' => '2024-09-05',
            ),
            62 => 
            array (
                'id' => 73,
                'id_prestashop' => NULL,
                'nombre' => 'ingrediente de prueba',
                'ref' => 'prueba',
                'descripcion' => 'prueba de creacion de articulo',
                'unidades_torre' => 0,
                'unidades_caja' => 10,
                'id_familia' => 2,
                'id_fabricante' => 1,
                'venta_stock' => 0,
                'peso' => '0.00',
                'cantidad' => 1,
                'id_tipo_etiqueta' => NULL,
                'precio' => '10.00',
                'principal' => 0,
                'ingrediente' => 1,
                'id_produccion' => NULL,
                'sorting_index' => 1,
                'created_at' => '2024-09-06',
                'updated_at' => '2024-09-24',
            ),
        ));
        
        
    }
}